test_trivia = [
    "If <user_name> and <user_name> were abc?",
    "What would <user_name> do when the question length is about average?",
    "Where does <user_name> hide?",
    "Who does <user_name> and <user_name> hate?",
    "Hey there this is <user_name>, nice to meet you from a question that is decently big in length",
    "Decently big question length by <user_name> for testing purpose to understand how it might impact?",
    "Another dummy entry by the <user_name> to keep the motives of the generated questions hidden from all",
    "Who is the idiot in the eyes of <user_name>?",
    "Enough entries from the <user_name> to manage the possible cases in hope for perfection"
]


truth_questions_1 = [
    # "What scares <user_name> the most?",
    # "What's the last thing <user_name> googled?",
    # "What does <user_name> spend too much time thinking about?",
    # "What's <user_name>'s hidden talent?",
    # "What's the weirdest thing <user_name> has eaten?",
    # "What does <user_name> spend too much time thinking about?",
    # "What's <user_name>'s hidden talent?",
    # "What's the weirdest thing <user_name> has eaten?",
    # "What's <user_name>'s most embarrassing childhood memory?",
    # "What's the strangest dream <user_name> has ever had?",
    # "What's <user_name>'s biggest pet peeve?",
    # "What's <user_name>'s guilty pleasure?",
    # "What's the craziest thing <user_name> has ever done for love?",
    # "What's <user_name>'s most irrational fear?",
    # "What's <user_name>'s weirdest habit?",
    "What's <user_name>'s favorite conspiracy theory?",
    "What's <user_name>'s most embarrassing moment in public?",
    # "What's <user_name>'s most embarrassing nickname?",
    "What's <user_name>'s most embarrassing childhood crush?",
    # "What's the silliest thing <user_name> has cried about?",
    # "What's <user_name>'s most embarrassing fashion faux pas?",
    "What's <user_name>'s secret talent that no one knows about?",
    "What's the most embarrassing thing <user_name> has ever said in public?",
    "What's the weirdest dream <user_name> has ever had?",
    # "What's <user_name>'s strangest phobia?",
    "What's <user_name>'s most embarrassing moment on a date?",
    "What's the silliest thing <user_name> has ever believed?",
    "What's the most embarrassing thing <user_name> has ever done at work?",
    "What's the weirdest thing <user_name> has ever done when no one was looking?",
    "What's the most embarrassing thing <user_name> has ever posted on social media?",
    "What's <user_name>'s biggest regret?",
    "What's <user_name>'s strangest superstition?",
    "What's the silliest thing <user_name> has ever done for a dare?",
    "What's the most embarrassing thing <user_name> has ever done in front of their crush?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's <user_name>'s most embarrassing moment at a family gathering?",
    "What's the craziest thing <user_name> has ever done on vacation?",
    "What's <user_name>'s most embarrassing moment in school?",
    "What's the silliest thing <user_name> has ever done in front of their parents?",
    # "What's the most embarrassing thing <user_name> has ever done while drunk?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's <user_name>'s most embarrassing moment at a party?",
    "What's the silliest thing <user_name> has ever done for money?",
    "What's the most embarrassing thing <user_name> has ever done on a road trip?",
    "What's <user_name>'s strangest habit when they think no one's watching?",
    "What's the craziest thing <user_name> has ever done on a dare?",
    "What's <user_name>'s most embarrassing moment in front of their siblings?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's the silliest thing <user_name> has ever done in public?",
    "What's the most embarrassing thing <user_name> has ever done in front of a celebrity?",
    "What's <user_name>'s most embarrassing moment in a job interview?",
    "What's the craziest thing <user_name> has ever done on a rollercoaster?",
    "What's <user_name>'s most embarrassing moment in front of their crush's parents?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's the silliest thing <user_name> has ever done on social media?",
    "What's the most embarrassing thing <user_name> has ever done on a date?",
    "What's the most embarrassing thing <user_name> has ever done in front of their in-laws?",
    "What's <user_name>'s strangest phobia?",
    "What's the craziest thing <user_name> has ever done for a friend?",
    "What's <user_name>'s most embarrassing moment at a wedding?",
    "What's the silliest thing <user_name> has ever done at work?",
    "What's the most embarrassing thing <user_name> has ever done at the beach?",
    "What's <user_name>'s most embarrassing moment at a sleepover?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's the silliest thing <user_name> has ever done at a theme park?",
    "What's the most embarrassing thing <user_name> has ever done in front of their significant other?",
    "What's <user_name>'s craziest superstition?",
    "What's the strangest habit <user_name> has that they're ashamed of?",
    "What's the silliest thing <user_name> has ever done while shopping?",
    "What's the most embarrassing thing <user_name> has ever done at a concert?",
    "What's <user_name>'s most embarrassing moment at a sleepover?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's the silliest thing <user_name> has ever done at a family gathering?",
    "What's the most embarrassing thing <user_name> has ever done in front of their neighbors?",
    "What's the most embarrassing thing <user_name> has ever done in front of their crush's friends?",
    "What's the weirdest dream <user_name> has ever had?",
    "What's the silliest thing <user_name> has ever done while drunk?",
    "What's the most embarrassing thing <user_name> has ever done at a wedding?"
]

# truth_questions_2 = [
    # "If <user_name> became famous overnight, it would be for this.",
    # "What is <user_name>'s biggest pet peeve?",
    # "If <user_name> could gift one item to everyone in the world, what would it be?",
    # "What is <user_name>'s most useless talent?",
    # "If <user_name> found a genie in a bottle, what would they wish for?",
    # "What is the weirdest thing in <user_name>'s pocket?",
    # "If <user_name> created their first signature fragrance, what would it be called?",
    # "If <user_name> had a museum, what would it be filled with?",
    # "If <user_name> got a tattoo tomorrow, what would it be?",
    # "If you were going to post an embarrassing status update on <user_name>'s Facebook, what would it say?",
    # "What song would <user_name> walk out to as a guest on the Ellen Show?",
    # "If <user_name> found $1,000, what would they buy first?",
    # "If <user_name> and <user_name> started a band, what would it be called?",
    # "What is the first search result when you google <user_name>'s name?",
    # "You find a brown paper bag with a note 'DO NOT OPEN' in <user_name>'s refrigerator. What's inside?"
# ]

truth_questions_3 = [
    # "If <user_name> were to write a book, what would the title be?",
    # "What is <user_name>'s most unusual hobby?",
    # "If <user_name> were a superhero, what would their superpower be?",
    # "What is <user_name>'s favorite conspiracy theory?",
    # "If <user_name> could time travel, where and when would they go?",
    # "What is the most embarrassing thing <user_name> has ever done in a job interview?",
    # "If <user_name> could have any animal as a pet, what would it be?",
    # "What is <user_name>'s go-to karaoke song?",
    "If <user_name> could live in any fictional universe, where would they live?",
    "What is <user_name>'s most prized possession?",
    "If <user_name> could have dinner with any historical figure, who would it be?",
    "What is the weirdest thing <user_name> has ever received as a gift?",
    # "If <user_name> could switch lives with anyone for a day, who would it be?",
    "What is <user_name>'s favorite childhood cartoon?",
    # "If <user_name> could only eat one food for the rest of their life, what would it be?",
    "What is <user_name>'s favorite ice cream flavor?",
    "If <user_name> could be any character from a TV show, who would they be?",
    # "What is <user_name>'s most irrational fear?",
    "If <user_name> could be any age for a week, what age would they choose?",
    "What is <user_name>'s favorite thing to do on a rainy day?",
    "If <user_name> could learn any language fluently, which one would it be?",
    "What is <user_name>'s favorite board game?",
    "If <user_name> could teleport anywhere right now, where would they go?",
    "What is <user_name>'s favorite type of cuisine?",
    "If <user_name> could be any fictional character, who would they be?",
    # "What is <user_name>'s weirdest habit when no one's watching?",
    "If <user_name> could have any job for a day, what would it be?",
    "What is <user_name>'s favorite childhood memory?",
    "If <user_name> could live in any era, which one would they choose?",
    # "What is <user_name>'s most used emoji?",
    "If <user_name> could have any talent they don't currently possess, what would it be?",
    # "What is <user_name>'s favorite movie quote?",
    "If <user_name> could have any car, what would they drive?",
    "What is <user_name>'s dream vacation destination?",
    # "If <user_name> could have any superpower, what would it be?",
    "What is <user_name>'s favorite TV show of all time?",
    # "If <user_name> could only listen to one song for the rest of their life, what would it be?",
    "What is <user_name>'s favorite outdoor activity?",
    "If <user_name> could have any mythical creature as a pet, what would it be?",
    "What is <user_name>'s most prized possession?",
    "If <user_name> could have dinner with any fictional character, who would it be?",
    "What is <user_name>'s favorite thing to do on a lazy Sunday?",
    "If <user_name> could live in any country for a year, where would they choose?",
    "What is <user_name>'s favorite childhood book?",
    "If <user_name> could have any job in the world, what would it be?",
    "What is <user_name>'s favorite season?",
    # "If <user_name> could have any animal as a pet, what would it be?",
    "What is <user_name>'s guilty pleasure TV show?",
    "If <user_name> could meet any celebrity, who would it be?",
    "What is <user_name>'s favorite thing to do on a long car ride?",
    "If <user_name> could have any dessert right now, what would it be?",
    "What is <user_name>'s favorite childhood toy?",
    "If <user_name> could have any skill instantly, what would it be?",
    "What is <user_name>'s favorite holiday?",
    "If <user_name> could visit any planet, which one would they choose?",
    # "What is <user_name>'s favorite movie genre?",
    # "If <user_name> could time travel, where and when would they go?",
    # "What is <user_name>'s favorite app on their phone?",
    # "If <user_name> could have any item from a movie, what would it be?",
    "What is <user_name>'s favorite way to relax after a long day?",
    "If <user_name> could live in any movie, which one would they choose?",
    "What is <user_name>'s most memorable birthday celebration?",
    "If <user_name> could have any job for a day, what would it be?",
    "What is <user_name>'s favorite type of cuisine?",
    "If <user_name> could learn any language fluently, which one would it be?",
    "What is <user_name>'s favorite board game?",
    "If <user_name> could teleport anywhere right now, where would they go?",
    "What is <user_name>'s favorite type of cuisine?",
    "If <user_name> could be any fictional character, who would they be?",
    "What is <user_name>'s favorite TV show of all time?",
    "If <user_name> could only listen to one song for the rest of their life, what would it be?",
    "What is <user_name>'s favorite outdoor activity?",
    # "If <user_name> could have any mythical creature as a pet, what would it be?",
    # "What is <user_name>'s most prized possession?",
    # "If <user_name> could have dinner with any fictional character, who would it be?",
    # "What is <user_name>'s favorite thing to do on a lazy Sunday?",
    # "If <user_name> could live in any country for a year, where would they choose?",
    # "What is <user_name>'s favorite childhood book?",
    # "If <user_name> could have any job in the world, what would it be?",
    # "What is <user_name>'s favorite season?",
    # "If <user_name> could have any animal as a pet, what would it be?",
    # "What is <user_name>'s guilty pleasure TV show?",
    # "If <user_name> could meet any celebrity, who would it be?",
    # "What is <user_name>'s favorite thing to do on a long car ride?",
    # "If <user_name> could have any dessert right now, what would it be?",
    # "What is <user_name>'s favorite childhood toy?",
    # "If <user_name> could have any skill instantly, what would it be?",
    # "What is <user_name>'s favorite holiday?",
    # "If <user_name> could visit any planet, which one would they choose?",
    # "What is <user_name>'s favorite movie genre?",
    # "If <user_name> could live in any movie, which one would they choose?",
    # "What is <user_name>'s most memorable birthday celebration?",
    # "If <user_name> could have any job for a day, what would it be?",
    # "What is <user_name>'s favorite type of cuisine?",
    # "If <user_name> could learn any language fluently, which one would it be?",
    # "What is <user_name>'s favorite board game?",
    # "If <user_name> could teleport anywhere right now, where would they go?",
    # "What is <user_name>'s favorite way to relax after a long day?",
    # "If <user_name> could live in any movie, which one would they choose?",
    # "What is <user_name>'s most memorable birthday celebration?",
    # "If <user_name> could have any job for a day, what would it be?",
    # "What is <user_name>'s favorite type of cuisine?",
    # "If <user_name> could learn any language fluently, which one would it be?",
    # "What is <user_name>'s favorite board game?",
    # "If <user_name> could teleport anywhere right now, where would they go?",
    # "What is <user_name>'s favorite way to relax after a long day?",
    # "If <user_name> could live in any movie, which one would they choose?",
    # "What is <user_name>'s most memorable birthday celebration?"
]

final_trivia = [
    "What scares <user_name> the most?",
    "What's the last thing <user_name> googled?",
    "What does <user_name> spend too much time thinking about?",
    "What's <user_name>'s hidden talent?",
    "What's the weirdest thing <user_name> has eaten?",
    "What does <user_name> spend too much time thinking about?",
    "What's <user_name>'s hidden talent?",
    "What's <user_name>'s guilty pleasure?",
    "What's <user_name>'s biggest fear?",
    "What's <user_name>'s most embarrassing nickname?",
    "What's <user_name>'s weirdest habit?",
    "If <user_name> became famous overnight, it would be for this.",
    "What is <user_name>'s biggest pet peeve?",
    "If <user_name> could gift one item to everyone in the world, what would it be?",
    "What is <user_name>'s most useless talent?",
    "If <user_name> found a genie in a bottle, what would they wish for?",
    "What is the weirdest thing in <user_name>'s pocket?",
    "If <user_name> created their first signature fragrance, what would it be called?",
    "If <user_name> had a museum, what would it be filled with?",
    "If <user_name> got a tattoo tomorrow, what would it be?",
    "If you were going to post an embarrassing status update on <user_name>'s Facebook, what would it say?",
    "What song would <user_name> walk out to as a guest on the Ellen Show?",
    "If <user_name> found $1,000, what would they buy first?",
    "If <user_name> and <user_name> started a band, what would it be called?",
    "What is the first search result when you google <user_name>'s name?",
    "You find a brown paper bag with a note 'DO NOT OPEN' in <user_name>'s refrigerator. What's inside?",
    "If <user_name> were to write a book, what would the title be?",
    "If <user_name> and <user_name> pick a place to go on a trip, where would they take everyone?",
    "If <user_name> were a superhero, what would their superpower be?",
    "What is <user_name>'s favorite conspiracy theory?",
    "If <user_name> could time travel, where and when would they go?",
    "If <user_name> could time travel, what would they do?",
    "What is the most embarrassing thing <user_name> has ever done in a job?",
    "If <user_name> could have any animal as a pet, what would it be?",
    "What is <user_name>'s go-to karaoke song?",
    "What is <user_name>'s spirit animal?",
    "What would you gift <user_name> on their birthday?",
    "If <user_name> could only eat one food for the rest of their life, what would it be?",
    "What is <user_name>'s weirdest habit when no one's watching?",
    "What is <user_name>'s most used emoji?",
    "What is <user_name>'s favorite movie quote?",
    "On checking <user_name>'s car, what would you find?",
    "If <user_name> could only listen to one song for the rest of their life, what would it be?",
    "If <user_name> could have any animal as a pet, what would it be?",
    "What is <user_name>'s favorite movie?",
    "What is <user_name>'s favorite movie genre?",
    "What is <user_name>'s favorite app on their phone?",
    "If <user_name> could have any mythical creature as a pet, what would it be?",
    "What is <user_name>'s most prized possession?",
    "What's the silliest thing <user_name> has cried about?",
    "What's <user_name>'s most embarrassing fashion faux pas?",
    "What's <user_name>'s strangest phobia?",
    "What might drunk <user_name> do?",
    "Where would <user_name> and <user_name> go to chill?",
    "If <user_name> could learn any language fluently, which one would it be?",
    "Where does <user_name> hide his cookies?",
    "For what would you expect <user_name> and <user_name> to fight?"
]


